Traceback (most recent call last):
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\coold\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_identity = pd.read_csv('train_identity.csv')
df_transaction = pd.read_csv('train_transaction.csv')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_15444/4275418521.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mdf_identity[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m'train_identity.csv'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mdf_transaction[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m'train_transaction.csv'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)[0m
[0;32m    946[0m     [0mkwds[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mkwds_defaults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    947[0m [1;33m[0m[0m
[1;32m--> 948[1;33m     [1;32mreturn[0m [0m_read[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    949[0m [1;33m[0m[0m
[0;32m    950[0m [1;33m[0m[0m

[1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    609[0m [1;33m[0m[0m
[0;32m    610[0m     [1;31m# Create the parser.[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 611[1;33m     [0mparser[0m [1;33m=[0m [0mTextFileReader[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    612[0m [1;33m[0m[0m
[0;32m    613[0m     [1;32mif[0m [0mchunksize[0m [1;32mor[0m [0miterator[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m   1446[0m [1;33m[0m[0m
[0;32m   1447[0m         [0mself[0m[1;33m.[0m[0mhandles[0m[1;33m:[0m [0mIOHandles[0m [1;33m|[0m [1;32mNone[0m [1;33m=[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1448[1;33m         [0mself[0m[1;33m.[0m[0m_engine[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_make_engine[0m[1;33m([0m[0mf[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1449[0m [1;33m[0m[0m
[0;32m   1450[0m     [1;32mdef[0m [0mclose[0m[1;33m([0m[0mself[0m[1;33m)[0m [1;33m->[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_make_engine[1;34m(self, f, engine)[0m
[0;32m   1703[0m                 [1;32mif[0m [1;34m"b"[0m [1;32mnot[0m [1;32min[0m [0mmode[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1704[0m                     [0mmode[0m [1;33m+=[0m [1;34m"b"[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1705[1;33m             self.handles = get_handle(
[0m[0;32m   1706[0m                 [0mf[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1707[0m                 [0mmode[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    861[0m         [1;32mif[0m [0mioargs[0m[1;33m.[0m[0mencoding[0m [1;32mand[0m [1;34m"b"[0m [1;32mnot[0m [1;32min[0m [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    862[0m             [1;31m# Encoding[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 863[1;33m             handle = open(
[0m[0;32m    864[0m                 [0mhandle[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    865[0m                 [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'train_identity.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'train_identity.csv'

